# Generated by Django 6.1.1 on 2026-09-22 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(default=0, help_text='Hierarchy level (e.g., 10=State, 20=District, 30=Mandal)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='persons', to='api.district'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='persons', to='api.state'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_teams', to='api.team')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.teamtype')),
            ],
            options={
                'unique_together': {('type', 'name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='persons', to='api.team'),
        ),
    ]
