# Generated by Django 6.1.1 on 2026-09-22 08:03

from django.db import migrations


def migrate_data(apps, schema_editor):
    State = apps.get_model('api', 'State')
    District = apps.get_model('api', 'District')
    TeamType = apps.get_model('api', 'TeamType')
    Team = apps.get_model('api', 'Team')
    Person = apps.get_model('api', 'Person')

    # Create base TeamTypes
    state_type, _ = TeamType.objects.get_or_create(name='State', defaults={'level': 10})
    district_type, _ = TeamType.objects.get_or_create(name='District', defaults={'level': 20})

    # Migrate States
    state_mapping = {}
    for state in State.objects.all():
        team, _ = Team.objects.get_or_create(
            name=state.state_name,
            type=state_type,
            defaults={'is_active': state.is_active}
        )
        state_mapping[state.id] = team

    # Migrate Districts
    district_mapping = {}
    for district in District.objects.all():
        parent_team = state_mapping.get(district.state_id)
        team, _ = Team.objects.get_or_create(
            name=district.district_name,
            type=district_type,
            parent=parent_team,
            defaults={'is_active': district.is_active}
        )
        district_mapping[district.id] = team

    # Update Persons
    for person in Person.objects.all():
        if person.district_id and person.district_id in district_mapping:
            person.team = district_mapping[person.district_id]
        elif person.state_id and person.state_id in state_mapping:
            person.team = state_mapping[person.state_id]
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teamtype_alter_person_district_alter_person_state_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
