# Generated by Django 6.1.1 on 2026-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_migrate_to_teams'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='api_person_state_i_07f19a_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='api_person_distric_3686c3_idx',
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['team'], name='api_person_team_id_740ba5_idx'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='district',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
