# Generated by Django 6.0.6 on 2026-09-23 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_team_description_teamtype_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstituencyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamtype',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Hierarchy level (e.g., 1=State, 2=District, 3=Constituency, 4=Mandal)'),
        ),
        migrations.AddField(
            model_name='team',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.constituencymaster'),
        ),
        migrations.AddField(
            model_name='constituencymaster',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='api.districtmaster'),
        ),
        migrations.AddField(
            model_name='team',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.districtmaster'),
        ),
        migrations.CreateModel(
            name='MandalMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandals', to='api.districtmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ConstituencyMandalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.constituencymaster')),
                ('mandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mandalmaster')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='mandal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.mandalmaster'),
        ),
        migrations.AddField(
            model_name='districtmaster',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.statemaster'),
        ),
        migrations.AddField(
            model_name='team',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.statemaster'),
        ),
        migrations.AddConstraint(
            model_name='constituencymaster',
            constraint=models.UniqueConstraint(fields=('district', 'name'), name='unique_district_constituency'),
        ),
        migrations.AddConstraint(
            model_name='mandalmaster',
            constraint=models.UniqueConstraint(fields=('district', 'name'), name='unique_district_mandal'),
        ),
        migrations.AddConstraint(
            model_name='constituencymandalmapping',
            constraint=models.UniqueConstraint(fields=('constituency', 'mandal'), name='unique_constituency_mandal'),
        ),
        migrations.AddConstraint(
            model_name='districtmaster',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='unique_state_district'),
        ),
    ]
