# Generated by Django 6.0.6 on 2026-09-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_constituencymaster_districtmaster_statemaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
