# Generated by Django 6.0.6 on 2026-09-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_person_designation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('mandal', 'type')},
        ),
    ]
